// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1VnXpQnLDG7TzhLQwUAvn4g9nLLMP2w',
    appId: '1:297651488892:web:bac791b8aa0fd3aa96e1f9',
    messagingSenderId: '297651488892',
    projectId: 'tiktokclone-12f50',
    authDomain: 'tiktokclone-12f50.firebaseapp.com',
    storageBucket: 'tiktokclone-12f50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgbnpS_O-W7mo7e9RygVonqw3pScvUEk',
    appId: '1:297651488892:android:72c1e52cedcabcbf96e1f9',
    messagingSenderId: '297651488892',
    projectId: 'tiktokclone-12f50',
    storageBucket: 'tiktokclone-12f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkpuK7hlNVwPBZ10W468Z6qpHHpbt4cA',
    appId: '1:297651488892:ios:c711660d6ccb403196e1f9',
    messagingSenderId: '297651488892',
    projectId: 'tiktokclone-12f50',
    storageBucket: 'tiktokclone-12f50.appspot.com',
    iosClientId: '297651488892-etvh504f9eej0c6ut461tmr3aciipn1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDkpuK7hlNVwPBZ10W468Z6qpHHpbt4cA',
    appId: '1:297651488892:ios:9bf7eecd3148029b96e1f9',
    messagingSenderId: '297651488892',
    projectId: 'tiktokclone-12f50',
    storageBucket: 'tiktokclone-12f50.appspot.com',
    iosClientId: '297651488892-vv4vee4oo40ga69m41r82fu3i9lk84c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone.RunnerTests',
  );
}
